import 'package:flutter/material.dart';

class PrivacyPolicy extends StatelessWidget {
  const PrivacyPolicy({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text('SmartLife Privacy Policy'),
        backgroundColor: Colors.white,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, size: 28, color: Colors.black),
          onPressed: () {
            Navigator.pop(context); // Better navigation handling
          },
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: SingleChildScrollView(
          child: Text(
            '''

Updated: December 9th, 2024
Volcano Technology Limited and its Affiliates (as hereinafter defined) (“we”, “us”, “our”, or “Volcano”) are committed to protecting your privacy. This SmartLife Privacy Policy (this “Policy”) describes our practices in connection with information privacy on Personal Data (as hereinafter defined) we process through your use of our products and services (collectively, the “Services”), for instance the SmartLife Mobile Application (the “App”) and the SmartLife MiniProgram.
Before you start using the Services, please carefully read this Policy which details our purposes for collecting and processing your Personal Data, as well as how we use, store, share and transfer your Personal Data. In this Policy you will also find ways to exercise your rights of access, update, delete or protect your Personal Data. 
If you are a customer located in the European Economic Area (“EEA”) or the United Kingdom (“UK”), the following corporate affiliate of Volcano may also process your personal data, including for purpose of provision of our products, services and support:
Tuya GmbH, in its role as the Data Controller, with its registered address at: Peter-Müller-Straße 16/16a, 40468 Düsseldorf, Germany.
If you have any question regarding this Policy, please do not hesitate to contact us via: 
Customer Service Department: 1-844-672-5646 or dpo@volcano-smart.com
Privacy Office: dpo@volcano-smart.com
You are not obliged to provide to us your Personal Data (as defined below). However, we may be unable to provide you with certain products and/or Services if you decline to provide such data.
If you are a children under the age of 16 (or such other age provided by applicable law in your country/region of residence), please read this agreement and the "SmartLife Children's Privacy Statement" with your legal guardian or parent and make sure that you and your guardian or parent have clear understanding about our privacy protection practices.
Definitions
In this Policy: 
Affiliate means any company, firm or legal entity that: (1) is directly or indirectly controlled by Volcano; or (2) directly or indirectly controls Volcano; or (3) jointly with Volcano, controls the same company; or (4) is, directly or indirectly, under common control of the same company with Volcano. Affiliates shall include, without limitation, Volcano’s parent companies, subsidiaries, and such subsidiaries under common control of the same parent company as Volcano.
Personal Data means information generated, collected, recorded and/or stored, electronically or otherwise, that can be used to identify an individual or reflect the activity of an individual, either from that information alone, or from that information and other information we have access to about that individual. 
Personal Sensitive Data includes personal biometric information, communication records and contents, health information, transaction information, and precise location information, etc. according to various data protection laws and regulations. When we collect Personal Sensitive Data from you, we will generate an explicit notification for your consent before we collection personal sensitive data about you. 
Smart Devices refers to those computing devices produced or manufactured by hardware manufacturers, with human-machine interface and the ability to transmit data that connect wirelessly to a network, including: smart home appliances, smart wearable devices, smart air cleaning devices, etc. 
1. What Personal Data Do We Collect?
In order to provide the Services to you, we will ask you to provide necessary Personal Data that is required to provide those Services. Please note that such Personal Data are necessary for carrying out relevant Services that you may require and you are obliged to provide such Personal Data in order to use our Services. If you do not provide your Personal Data, we may not be able to provide you with the Services. 
1) Information You Voluntarily Provide to Us
In Login mode:
• Registered Account Data: When you register an account with us, we may collect your account name and contact details, such as your email address, phone number, user name, and login credentials. During your interaction with the Services, we may further collect your nickname, country code, language preference or time zone information into your account.
• Feedback: When using feedback and suggestion features in the Services, we will collect your email address, mobile phone number and your feedback content(Added image or video) to address your problems and solve device failures on a timely basis.
If you authorize login to the Services with a third-party account, we will obtain from such third party your account information (such as portrait, nickname, region etc.) which may be bound with your Tuya account for quick login. We will ensure compliance with applicable data protection laws and regulations, as well as agreements, policies or documentations agreed with such third party regarding sharing personal information, in processing your Personal Data.
In Try as guest mode:
• Non-registered Account Data: If you do not want to provide your account data when you start to use any of the Services, you may use the App without logging in or creating an account, namely the “Try Now” mode, and you may still use certain Services, such as searching and browsing any features on the App by creating a guest ID. When you are using the "Try Now" mode, we will not collect Personal Data related to your account; the data being collected is exclusive to the time of entering the App, operating system of your mobile phone, etc. Collection and use of the Personal Data collected here will be limited for the purposes you have authorized in using the additional functions of the App and/or the Smart Devices. For instance, if you enable the location setting in the "Try as guest" mode, the location data will be uploaded for supporting the function. Once you exit from the "Try Now" mode, we will remove your data instantly and permanently.
However, if the Services you request or purchase are based on your account, please go to the registration/login page for guidance.
At the same time, based on different application products and services, Tuya will collect corresponding and necessary personal information in order to provide you with products and services.
Information based on additional functions:
In order to offer you with more convenient and higher-quality Services with optimized user experiences, we may collect and use certain information if you consent to use of additional functions in the App. Please note, if you do not provide such information, you may continue to use basic Services of the App and connected Smart Devices, but certain features based on these additional functions may not be available. These additional functions may include:
Additional functions based on location information:
• When you enable the location-based functions through permission settings on your mobile device, we will collect and process your location information to enable these functions, such as pairing with your Smart Devices. Also, we may collect information about your: a) real-time and precise location, for instance when you choose to use the automation scenarios for controlling your Smart Devices, or b) non-precise geo-location when you use certain Smart Devices or the Services, such as robot cleaner and weather service.
• Based on your consent, when you enable the geo-fence feature, your location information will be generated and shared with Google Maps services. Please note that Google has corresponding data protection measures, which you may refer to Google’s Data Processing and Security Terms for more details. You may disable the collection and use of your location information by managing the device level settings, upon which we will cease to collect and use your location information. 
• You may opt out of the use of your location information ("My - Setting - Privacy Right Setting - Switch on/off Location Information").

Additional services based on camera:
• You may use the camera to scan the code by turning on the camera permission to pair with a Smart Device, take video, etc. Please be aware that even if you have agreed to enable the camera permission, we will only obtain information when you actively use the camera for scanning codes, video recording, etc. 
• You may opt-out the using of camera permission: "My - Setting - Privacy Right Setting - Switch on/off Camera".
Additional services for accessing and uploading pictures/videos based on photo albums (picture library/video library):
• You can use this function to upload your pictures/videos after turning on the album permissions, so as to provide proof for reporting equipment usage problems and upload pictures/videos on some special equipment panels. When you use the photos and other functions, we will not recognize this information; but when you report a device usage problem, we may use the photos/pictures you upload to locate your problem.
• You may opt-out the using of photo album permission: "My - Setting - Privacy Right Setting - Switch on/off Photo Album".
Additional services related to microphone-based service:
• After turning on the microphone permission, you can use the microphone to implement voice functions, including shooting videos, waking up voice/AI assistants, and some special panels (such as video doorbell calls). In these functions, we will collect your voice information to identify you. Instruction needs or provide you with corresponding services. Please know that even if you have agreed to turn on the microphone permission, we will only obtain voice information through the microphone when you actively click the microphone icon in the App or record a video.
• You may opt-out the using of microphone permission: "My - Setting - Privacy Right Setting - Switch on/off Microphone".
Additional services based on storage permission (Android):
• We apply for this permission from you to ensure the stable operation of the client. After you enable us to read/write your device storage, we will read or write pictures, files, videos and other necessary information from your device storage space to provide you with information release or in The function of recording crash log information locally.
• You may opt-out the using of storage permission: "My - Setting - Privacy Right Setting - Switch on/off Storage".
Additional services based on Notification permission:
• The reason why we ask you for the permission is to send you notifications about using the products and services, especially if you have purchased security services and you require an alert or message so that you can capture the real-time status.
• You may opt-out the using of App notifications: "My - Message Center - Setting - Switch on/off Notifications".
Additional services based on Alert Window permission：
• You may choose to bind a camera in the App and require the App to display the real-time image of the camera in a separate window.
• You may opt-out the using of alert window information: "My - Setting - Privacy Right Setting - Switch on/off Alert Window".
Additional services based on Bluetooth permission:
• You can enable Bluetooth functions after turning on the permission, including controlling the Smart Devices, acquiring device status, and device network configuration. In these functions, we will communicate with terminal devices via Bluetooth. Please be aware that even if you have agreed to enable the Bluetooth permission, we will only use Bluetooth for communication in these scenarios: display device status on the home page and device panel; perform device control on the home page and device panel; we will use it on the home page and the add device page, for discovering the devices via distribution network.
• You may opt-out the using of Bluetooth via "My - Settings - Privacy Setting - Disable/Enable Bluetooth permission".
Additional services based on HomeKit permission (iOS):
• You can enable related functions after enabling HomeKit permissions, including discovering Smart Devices, enabling Smart Device network configuration, controlling Smart Devices, and checking device status. Among these functions, we will process data with the "Home“ App that comes with the iOS system through HomeKit. Please be aware that even if you have agreed to enable the HomeKit permission, we will only use it in these scenarios: on the home page, to discover HomeKit devices, HomeKit device network configuration; in "Settings - HomeKit" for discovering HomeKit devices, HomeKit device network configuration.
• You may opt-out the using of HomeKit permission via "My - Settings - Privacy Settings-Turn off/on HomeKit permission".
Additional services based on HealthKit (iOS):
• You can proactively enable related functions after enabling HealthKit permission, including statistics on weight, height, running, and swimming. In these functions, we will exchange data with the health-related functionalities that comes with the iOS system through HealthKit. Please be aware that even if you have agreed to enable HealthKit permission, we will only use them in these scenarios: when you use the health-related Smart Device, such as body fat scales, bracelets, watch and consent to use the HealthKit, the data reported by the Smart Device will be transferred to HealthKit.
• You may opt-out the using of HealthKit permission via "My - Settings - Privacy Settings - Turn off/on HealthKit permission".
Please note that if you turn on any permission, you authorize us to collect and use relevant personal information to provide you with corresponding Services. Once you turn off any permission, we will take it as a cancellation of the authorization, and we will no longer continue to collect Personal Data based on the corresponding permissions, and the related functions may be terminated. However, your decision to turn off the permission will not affect previous collection and use of information based on your authorization.
2) Information We Collect Automatically
• Mobile Device Information: When you interact with our Services, in order to provide and maintain the common operation of our Services, improve and optimize our Service, and protect your account security as well, we automatically collect mobile device information, such as mobile device model number, IP address, wireless connection information, the type and version of the operating system, application version number, push notification identifier, log files, and mobile network information. Meanwhile, we will collect your software version number. In order to ensure the security of the operating environment or to provide services, we will collect information about the installed mobile applications and other software you use.
• Service log information: When you use our application, in order to provide you with a better user experience and improve and optimize our services, system and exception logs will be uploaded for analysis, including your IP address, usage habits, The version of the operating system, the date or time of access, and usage information allow us to accurately identify problems and help you solve problems when using the service.
Please note that one cannot identify a specific individual by using device information or log information alone. However, as these types of information, combined with other information, may be used to identify a specific individual, such information will be treated as Personal Data. Unless we have obtained your consent or unless otherwise provided by data protection laws and regulations, we will aggregate or pseudonymize such information. Additionally, please refer to section titled “Data Retention” of this Policy for data retention periods of such Personal Data..
3) Smart Devices Related Information:
When you use a Smart Device, we will collect some basic and pre-embedded information of the Smart Device and the information generated during your use of the Smart Device.
• Basic Information of Smart Devices: When you connect your Smart Devices with the Services, we may collect basic information about your Smart Devices such as device name, device ID, online status, activation time, firmware version, and upgrade information.
• Information collected during the process of connecting smart devices: When using Tuya APP and services, in order to facilitate device identification/activation/control, perform data statistics and analysis, and ensure the safety and quality of network access and service operations, we will use the products according to your use When performing specific operations, we will receive and record information related to the device you are using based on the type of smart device you need to connect to. We will collect the following information:
Wi-Fi information (SSID, BSSID, Wi-Fi Mac address, Wi-Fi password), device Mac address, device ID, device IP, device Bluetooth Mac address.
• Information Reported by Smart Devices: Depending on the different Smart Devices you elect to connect with the Services, we may collect different information reported by your Smart Devices. The following information reported by the Smart Device only applies when you use them:
When you voluntarily use a smart camera (IPC service) and connect to the Tuya platform: When you connect a doorbell camera, a door lock, or a smart surveillance camera through Tuya service to monitor the security of your residence, during the process, the device may capture the images if it recognizes someone or an object is moving around, and then provide you a playback of related surveillance content. At this time, we will automatically encrypt the captured image and save it locally on the device. When you actively choose and successfully purchase cloud storage service, the smart camera will upload the pictures or video files you have taken to the cloud for further storage so that you can review them in the App. We will keep your information based on the cloud storage service you purchase. When you choose to delete the picture in advance in the Tuya App, you can delete it in the message center and if you need to delete a video on the App, the cloud will delete immediately the video files you stored in the cloud service.Please note that when you choose to turn off the motion detection function, the smart camera will not actively record the captured images, which will affect your original intention of using the smart camera. 
For example: when you voluntarily use a certain health-related smart device and connect to the Tuya platform: If you choose one or more smart devices, the corresponding information will be recorded:
• Smart body fat scale or fitness tracker: height, weight, body fat mass (BFM), body mass index (BMI) and skeletal muscle mass (SMM), body fat rate, muscle mass, body fat index, obesity level, ideal Weight, weight control, visceral fat index, net weight, body water, bone mass, protein rate, BMR, metabolic age, body score, body shape, subcutaneous fat rate, subcutaneous fat mass, heart rate;
• Bracelets and similar smart devices: heart rate, steps, calories, mileage, heart rate, sleep records, training records, body temperature, blood oxygen, systolic blood pressure, diastolic blood pressure, and pressure.
• Smart fitness equipment represented by smart skipping ropes: start time, jumping mode, number of rope skipping, exercise duration, calories burned, maximum number of jumps to maintain, number of rope skipping, average speed, maximum speed, and heart rate during exercise.
In particular, when you actively agree and enable the sharing function connected with a third-party health platform, such as Apple Health, Google Fit, and Fitbit, we will share your health information with the third party only for the purpose of being relevant to you. Measure and analyze health status. At the same time, we will not upload your personal information. Your information will be uploaded locally from your device to the third-party cloud platform.
The purpose of sharing information is to measure and analyze health indicators related to you. Otherwise, we will not disclose such health information to any other third party or use health-related information for other purposes not defined in this policy. You can disconnect the authorized connection between the Tuya App and the third-party health platform at any time by managing your health settings in the health management center on your mobile device. When we add new third-party sharing channels, we will never share your information if you do not use that channel.
2. Purposes and Legal Basis for Processing Personal Data
The purpose for which we may process information about you are as follows:
• Provide You with Services: We process your account data, mobile device information, usage data, location information, and Smart Device related information to provide you with the Services and Services that you have requested. The legal basis for this processing is to perform our contract with you according to our User Agreement.
• Safety of Our Services: We process your mobile device information, usage data, location information and Smart Device related information to ensure the authentication, integrity, security, and safety of accounts, activity, and products and Services, to develop and upgrade the Services, to study in-depth the efficiency of our operations and to prevent and trace fraudulent or inappropriate usage. The legal basis for this processing is as necessary for our (or others’) legitimate interests. 
• Non-marketing Communication: We process your Personal Data to send you important information regarding the Services, changes to our terms, conditions, and policies and/or other administrative information. At the same time, we will also send you notifications related to the services you have purchased, such as alert services. You can check the “App Notification” in the App ("Me > Message Center > Setting > Notification Setting”) to manage these communications. When you decide not to enable the Notifications function, we will no longer process your information for such purpose. The legal basis for this processing is to perform our contract with you according to our User Agreement. 
• Data Analysis: In order to analyze the usage of the products we provide and improve your user experience, we may analyze the data you provide us; specifically: a) we need to check your problems when you encounter any malfunctions during the usage of the product, under such circumstance, you may not be able to opt-out because it is highly relate to functionalities and quality of our products and services, and b) analyze data about how you interface with the product or under particular scenarios so that you can better enjoy the convenience brought by our Services. Your consent is required prior to processing under such circumstance; if you do not agree to data analysis of your data, you can enter the privacy settings of the App (“My > Settings > Privacy Settings > Data Analysis”) to opt-out your selection. The legal basis for such processing is based on your consent.
• Marketing Communication and Personalization: We may process your account data, usage data, device information to personalize product design and to provide you with services tailored for you, such as recommending and displaying information and advertisements regarding products suited to you, and to invite you to participate in surveys relating to your use of the Services. The legal basis for this processing is your consent. You may give consent to such processing by proactively electing to turn on the Personalization option in the App, and we will not process your Personal Data for such purpose unless your consent has been given to us. If you do not wish for us to continue to process your Personal Data for personalization, you may opt out when you enter the App, or by changing your preferences in “Privacy Settings” (“Me> Settings > Privacy Settings > Personalization”) in the App. The legal basis for this processing is your consent. Please note: as of the date of latest update of this Policy, we do not use automated decision-making in our Services to process your Personal Data. 
https://privacy.truste.com/privacy-seal/validation?rid=fa1b2818-04fe-4723-af4b-9bc0d6fcc1bc 
Data Retention
We process your Personal Data for the minimum period necessary for the purposes set out in this Policy, unless there is a specific legal requirement for us to keep the data for a longer retention period. We determine the appropriate retention period based on the amount, nature, and sensitivity of your Personal Data, and after the retention period ends, we will destroy your Personal Data. 
In detail, the following factors are considered when determining our retention periods of Personal Data:
• The period of time during which an ongoing relationship with you is retained and Smart Devices and/or our Services are provided to you (also see the User Agreement). For instance, your Personal Data is retained for as long as your account with us remains valid or you keep using the Smart Devices and/or our Services;
• Whether we have a legal obligation to keep your Personal Data; or
• Whether retention is advisable in light of our legal position (such as in regard to the enforcement of our agreements, the resolution of disputes, and applicable statutes of limitations, litigation, or regulatory investigation). 
If the legal basis is your consent, we will delete your data immediately after you withdraw your consent. 
If the legal basis is our legitimate interest, we will delete your data as quickly as possible if there are no overriding legitimate grounds for processing, but in any case in the event of direct advertising. Personal Data will no longer be retained when you request to remove your Personal Data or withdraw your consent, and we will accordingly complete the task.
When we are unable to do so for technical reasons, we will ensure that appropriate measures are put in place to prevent any further such use of your Personal Data.
Dispute Resolution
If you have an unresolved privacy or data use concern that we have not addressed satisfactorily, please contact our U.S.-based third-party dispute resolution provider (free of charge) at https://feedback-form.truste.com/watchdog/request.
Children’s Privacy
Protecting the privacy of young children is especially important to us. The Services are not directed to individuals under the age of thirteen (13) (or such other age provided by applicable law in your country/region of residence), and we request that these individuals do not provide any Personal Data to us. We do not knowingly collect Personal Data from any child unless we first obtain permission from that child’s parent or legal guardian. If we become aware that we have collected Personal Data from any child without permission from that child’s parent or legal guardian, we will take steps to remove that information.
Your California Privacy Rights
California Civil Code Section 1798.83 permits users of the Software that are California residents to request certain information regarding our disclosure of Personal Data to third parties for their direct marketing purposes. To make such a request, please contact us in accordance with the "Contact Us" section below. We do not disclose Personal Data to third parties for their direct marketing purposes without your consent. Visit our Statement on California Privacy Notice page for more information.
Changes to this Policy
We may update this Policy to reflect changes to our information practices, at least on an annual basis. If we make any material changes we will notify you by email (send to the e-mail address specified in your account) or by means of a notice in the mobile applications prior to the change becoming effective. We encourage you to periodically review this page for the latest information on our privacy practices.
Contact Us
If you have any questions about our practices or this Policy, please contact us as follows:
Volcano Technology Limited
Postal Mailing Address: Suite 603, 6/F Laws Commercial Plaza, 788 Cheung Sha Wan Road, Kowloon, Hong Kong
Email: dpo@volcano-smart.com.
For European Union or United Kingdom data subjects, you have the right to lodge a complaint with a supervisory authority concerning our data processing activities. For questions, or to exercise your rights as an EU or UK data subject, please contact our EU/UK Representative here:
Name: Rickert Rechtsanwaltsgesellschaft mbH
Email: art-27-rep-hangzhoutuya@rickert.law
Emailing Address: Colmantstraße 15, 53225 Bonn, Germany
You may contact our Data Protection Officer, Mr. Will Yu, by sending an email to dpo@volcano-smart.com.
''',
            style: TextStyle(fontSize: 14.0),
          ),
        ),
      ),
    );
  }
}
